domain: bigbang.dev

# Uncomment the following settings if using the AWS RKE2 terraform setup
# istio:
#   ingressGateways:
#     public-ingressgateway:
#       type: "NodePort"
#       nodePortBase: 30000

istiooperator:
  enabled: false

istio:
  enabled: true
  git:
    repo: "https://github.com/tetrateio/tetrate.git"
    path: "./helm/controlplane"
    tag: "1.6.0"
    existingSecret: github-deploy
  values:
    image:
      registry: gcr.io/timm16-mcte-0
      tag: 1.6.0
    operator:
      deployment:
        env:
          - name: ISTIO_ISOLATION_BOUNDARIES
            value: "false"
    spec:
      components:
        gitops:
          enabled: true
          reconcileInterval: 60s
        internalCertProvider:
          certManager:
            managed: INTERNAL
        xcp:
          centralAuthMode: JWT
          configProtection: {}
          enableHttpMeshInternalIdentityPropagation: false
          kubeSpec:
            deployment:
              env:
                - name: ENABLE_GATEWAY_DELETE_HOLD
                  value: "true"
                - name: GATEWAY_DELETE_HOLD_SECONDS
                  value: "20"
            overlays:
              - apiVersion: install.xcp.tetrate.io/v1alpha1
                kind: EdgeXcp
                name: edge-xcp
                patches:
                  - path: spec.components.edgeServer.kubeSpec.deployment.env[-1]
                    value:
                      name: ENABLE_ENHANCED_EAST_WEST_ROUTING
                      value: "true"
                  - path: spec.components.edgeServer.kubeSpec.deployment.env[-1]
                    value:
                      name: DISABLE_TIER1_TIER2_SEPARATION
                      value: "true"
                  - path: spec.components.edgeServer.kubeSpec.deployment.env[-1]
                    value:
                      name: ENABLE_DNS_RESOLUTION_AT_EDGE
                      value: "true"
          rateLimitServer:
            backend:
              redis:
                uri: redis-master.tsb-ratelimit.svc.cluster.local:6379
      hub: gcr.io/timm16-mcte-0
      managementPlane:
        clusterName: gke-bigbang
        host: timm16.gcp.cx.tetrate.info
        port: 443
        selfSigned: true
      meshExpansion: {}
      telemetryStore:
        elastic:
          host: 34.170.140.66
          port: 9200
          protocol: https
          selfSigned: true
          version: 7
    secrets:
      clusterServiceAccount:
        JWK: |-
      {"alg":"RS256","d":"SEbzyWLm1Dn7ni17LTLYVWo8WwHyC4BIv_jLcMun5OOzeTtxhuoOQIJqjv17nf9UQANU-bl3KBQPmafR863TmW_OtCjRLzt7-M9yG9vTOHrUiUVCmLR-dFhwbOLVsYyXHvvQrZKvu0aOyY9U9KLSO8rb55XJoaO3mXBypiB1bVNeyLenH8kxnYdV6vEmKajyS_FwK5jm-U0e4nEecIaEaenm8O6MYc1SAqXzsFsWmLmnKh8SQyZJ6hF0DlIH2gMJdc7FBIOhbH3Sugbijmy-ueDYynMpMJgnh-8aoq_cHQEWbzX9kaA7COjI96QrqnFyh9Us48AczoNvRckwxUNAcQ","dp":"e5xladbfryNvOxFAOIijrFlz7uVxOpTTH1Mcd2VS43V4QNJHWHYrhlGJuSOUxS2_BXeuEIKWE0ItNagkeZUeAheYqcbmmjQRW6JdHpdACzZ0wHdom17vg1bHmj1joZXetlX_OTrecUYJ5PYRNXIlnpwy53tb9ddP7AFA3QyF5QE","dq":"qt7gD_zsjiX6g_y5McOAmBtRx7yDEv641SXoQ8ulr8OoYU8VfqQr5JkmHpXbIa3XSlR8EGJuLf6D5cePGUMlo-sUtyMpWeVdWbNjOTN0gSuk4r0Zp0k6ADLpvlxF9Cg_agoXvhdzg3W7lIx90frc4eSb1b9AWW3wi3wtG-sprwc","e":"AQAB","kid":"1o2y4A9WGsDOPYY6TnZiA5SCXw_xZydM6i5A4_SmZlE","kty":"RSA","n":"lrmMBaBSCbuW_B-VmrK_vUo_ZrawCzpJIrjbfrvuPxg0TdVBtzBa7cAlKBYMMsGlO8NFwvmMKYFDmaaST9gL_BXMqh1BLOngpA2LwL0bWR_RX7hpv9HKMf2Dfj8mxO_JfAMXuVJCZ54i2VUi-EzjQhzRTasUxoJki6-FBLm41gVELlTeWLws5mk6V_yojYYA_emaY5ad60rmfU1IuT8gLRPXuc3DjlM1FM8YB42hgvKrea1oS4HapGBbeoVdBuRXzPZR78Yo153pIPwAE6vcf1vGDKSt4T3F4pz4arWx6vwzypnfyuCa_4EmCP2Ra5ftKZPHwlFjUw9l0lGVXLIwQw","p":"w8q_S86Pxv-YC-HgYdyJVhuFscDXnEA7uCsito6dp1pBrB4lFyY8kB4xkDfrQ-0E3uDWq8J3UxuF_PbbL0eeu6Ehd_qOwcxld7UdgZxnKuelqShyKG-7tTLzbxpRw2AGzqF-m_qaTwaA9YGfQSjBV1MQ2hMHO-l3AxN7iOSyGck","q":"xRL-YvKy03D4qS0wKt_ybbOghWs5LGqAqNBYfXqbb7aC8_kg77ic221Erkw6HX7bmBc0IkA6mxTtHrWp0aImv-qhTklfykrBlcLi6Zbv3qBChpkLRPA0vElDevqgbsjCdJxgCLftob9YhjhDSHXjLdRMVDm2V76zhXYZE5OOv6s","qi":"mCi3a2g-d6_nh8JwjnWF9MZt1pSlaSygGnukzWeivhgCnE68VFYOkV0Pu8WyXUmaAR34E5EZkU7C-BW157nR8tO33Y60JwaQGGljYJCcIwbTY9PSPmBiledKgX_Hrq3UoRawI105nIWNyP2N0RyrZjtKWgGYKedg2cCZiJKwR20"}
        clusterFQN: organizations/tetrate/clusters/gke-bigbang
      elasticsearch:
        cacert: |-
          -----BEGIN CERTIFICATE-----
          MIIDLjCCAhagAwIBAgIRANf0loASs10Np52wCGDUeq4wDQYJKoZIhvcNAQELBQAw
          ITEMMAoGA1UECxMDdHNiMREwDwYDVQQDEwh0c2ItaHR0cDAeFw0yMzAxMDUxMzM5
          MjNaFw0yNDAxMDUxMzQ5MjNaMCExDDAKBgNVBAsTA3RzYjERMA8GA1UEAxMIdHNi
          LWh0dHAwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC8aL5NS+UDreJw
          1ODQ54O03AHp9FrGlNjIMrLUKi2ZSUxfX+gqnwqZYyUFjiPPf+tr3vcthhwL0la/
          MhHwDXfFAH9q6pHToMogE+obapY2lNoObLNfQxxiN+MtNzqD+dPa1d803QLKWTgE
          ZPMhHw7mfbtkHw0Gcqj7C3SO4vbWDfUCdsHljDxlZroiN6oVk+0bV0OW9yA3/T4P
          DFRRr4uA/pj/K77/W+CE3d3P2DbSz1m/FRmFYwlpCLeEoslsXaLW+rP0asXdMUSF
          rFsrNFmZWwmjyXQUbh7Y7Y5ITFjGbplbQjslUyOnFiY30mPQYekJASSOkKsjvQwn
          1kwSsRjBAgMBAAGjYTBfMA4GA1UdDwEB/wQEAwIChDAdBgNVHSUEFjAUBggrBgEF
          BQcDAQYIKwYBBQUHAwIwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUNb12THWc
          PZv9acJmRAGtgGVy/0UwDQYJKoZIhvcNAQELBQADggEBAAKZvL9AfEJ8XbxNWpE/
          BZUtAzpo+9TkRTqRZyPkVEUDInozJ760MPpZAPksCvFF4KfLMn3aS6FoLNmmkMjL
          VVqehkh8OFY9R/V3A7XPCjxlX9ShCTYA9FfuQ23OYAlAej6ul4M8PGPITM7E5INR
          1aXCumtOGvlNVGkFhqQ77Ma0jRWPhE3b8gz+mWpFonVWM771204p4+mn/Kg+cp0S
          uX72sGlle6QpQEQGNC0bDhTBiGY0IngFZsP4CjKZ4chWa1XkMz89I7JtETmSyVkF
          r0ujaxTVqBvvPN0pDu8/ywy1eWyNHNRmVAZ55ar0BD7BIlHqqHq1mM11mNXo+Gbc
          fok=
          -----END CERTIFICATE-----
        password: JUBxel9c16lN75zx687c7jZ6
        username: elastic
      tsb:
        cacert: |
          -----BEGIN CERTIFICATE-----
          MIIDKjCCAhKgAwIBAgIQawMFrLrPq8FzqNkTIuqY8zANBgkqhkiG9w0BAQsFADAv
          MRUwEwYDVQQKEwxjZXJ0LW1hbmFnZXIxFjAUBgNVBAMTDXNlbGZzaWduZWQtY2Ew
          HhcNMjMwMTA1MTM0OTQ4WhcNMjUwNjIzMTM0OTQ4WjAvMRUwEwYDVQQKEwxjZXJ0
          LW1hbmFnZXIxFjAUBgNVBAMTDXNlbGZzaWduZWQtY2EwggEiMA0GCSqGSIb3DQEB
          AQUAA4IBDwAwggEKAoIBAQDpKv7gLdYCWYHQuF+jq1+lHew2+2JeJVGarHYU8DdH
          Rfu6fWz8K95QaNN5VsrkxqJ65jGUesfSzWc09LdjhWbtLynPlUCqix9ywAR6PL7p
          K87lBtEt4r1Sfn4S+cJK1+BZfdF9WocHhzFTTWoEAI2Ca154XfQ0emC1eN/X2cV+
          ++SLKoDANfCqtmv3LPPE0f871zbE+txAdD86UbkS8sGWx4+hJ67m89yf7SPvL/tD
          b2MV3fV+uqdSccAc7yUeluiv/a3xKFalHdxP+ka2t/CdGkkGu22IZ2KkABnTJ7cm
          yCszzkffyA2kECHc29PaMvIcwwBiGLvHVf//nKqri+7pAgMBAAGjQjBAMA4GA1Ud
          DwEB/wQEAwICpDAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBSyxlWa+VQSx1VB
          tXIPA/kIQz4IZTANBgkqhkiG9w0BAQsFAAOCAQEArZGmtboCNDKwQnjOyitl/rvZ
          dtVPXF/GhnLjbbfBNOYmV6r5ckkxPU+vvOt7JRAyp5VP7dNQwrk4VAq2uvnIgqNZ
          bSCS2KDvyqgIMm9h20l//F8Ezy+56o3UgAXIG4TA4F5H5MjsdUFWO3LmvyXB2lPv
          CVnohUjxZ120u3YLrGtg0zZZmdnzhTGwdGSJ6NuNSoNxCCjo293tARKJeel7j8oo
          90Neli97pccF4WTrMtihm08mJwuJqfd0qqiy8ryhJT9x8jqiu+btxS6N6wbjligL
          pJXIbNC3ZglN3QTFkt79IKQTUacUJGiuSDRnI9owdso1fZq7qa5N7QS4qQpMeA==
          -----END CERTIFICATE-----
      xcp:
        rootca: |
          -----BEGIN CERTIFICATE-----
          MIIDKjCCAhKgAwIBAgIQawMFrLrPq8FzqNkTIuqY8zANBgkqhkiG9w0BAQsFADAv
          MRUwEwYDVQQKEwxjZXJ0LW1hbmFnZXIxFjAUBgNVBAMTDXNlbGZzaWduZWQtY2Ew
          HhcNMjMwMTA1MTM0OTQ4WhcNMjUwNjIzMTM0OTQ4WjAvMRUwEwYDVQQKEwxjZXJ0
          LW1hbmFnZXIxFjAUBgNVBAMTDXNlbGZzaWduZWQtY2EwggEiMA0GCSqGSIb3DQEB
          AQUAA4IBDwAwggEKAoIBAQDpKv7gLdYCWYHQuF+jq1+lHew2+2JeJVGarHYU8DdH
          Rfu6fWz8K95QaNN5VsrkxqJ65jGUesfSzWc09LdjhWbtLynPlUCqix9ywAR6PL7p
          K87lBtEt4r1Sfn4S+cJK1+BZfdF9WocHhzFTTWoEAI2Ca154XfQ0emC1eN/X2cV+
          ++SLKoDANfCqtmv3LPPE0f871zbE+txAdD86UbkS8sGWx4+hJ67m89yf7SPvL/tD
          b2MV3fV+uqdSccAc7yUeluiv/a3xKFalHdxP+ka2t/CdGkkGu22IZ2KkABnTJ7cm
          yCszzkffyA2kECHc29PaMvIcwwBiGLvHVf//nKqri+7pAgMBAAGjQjBAMA4GA1Ud
          DwEB/wQEAwICpDAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBSyxlWa+VQSx1VB
          tXIPA/kIQz4IZTANBgkqhkiG9w0BAQsFAAOCAQEArZGmtboCNDKwQnjOyitl/rvZ
          dtVPXF/GhnLjbbfBNOYmV6r5ckkxPU+vvOt7JRAyp5VP7dNQwrk4VAq2uvnIgqNZ
          bSCS2KDvyqgIMm9h20l//F8Ezy+56o3UgAXIG4TA4F5H5MjsdUFWO3LmvyXB2lPv
          CVnohUjxZ120u3YLrGtg0zZZmdnzhTGwdGSJ6NuNSoNxCCjo293tARKJeel7j8oo
          90Neli97pccF4WTrMtihm08mJwuJqfd0qqiy8ryhJT9x8jqiu+btxS6N6wbjligL
          pJXIbNC3ZglN3QTFkt79IKQTUacUJGiuSDRnI9owdso1fZq7qa5N7QS4qQpMeA==
          -----END CERTIFICATE-----

flux:
  interval: 1m
  rollback:
    cleanupOnFail: false

logging:
  values:
    elasticsearch:
      master:
        count: 1
        persistence:
          size: 256Mi
        resources:
          requests:
            cpu: 200m
            memory: 1Gi
      data:
        count: 1
        persistence:
          size: 256Mi
        resources:
          requests:
            cpu: 200m
            memory: 1Gi
    kibana:
      count: 1
      resources:
        requests:
          cpu: 200m
          memory: 512Mi

monitoring:
  enabled: true
  values:
    prometheus:
      prometheusSpec:
        resources:
          requests:
            cpu: 200m
            memory: 1Gi

fluentbit:
  values:
    securityContext:
      privileged: true

gatekeeper:
  values:
    replicas: 1
    controllerManager:
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
    violations:
      allowedDockerRegistries:
        parameters:
          repos:
            - gcr.io
      hostNetworking:
        parameters:
          excludedResources:
            - purelb/allocator-.*
            - purelb/lbnodeagent-.*


    audit:
      resources:
        requests:
          cpu: 200m
          memory: 256Mi

kyverno:
  values:
    replicaCount: 1

twistlock:
  enabled: false
  values:
    console:
      persistence:
        size: 256Mi

metrics-server:
  values:
    args:
    - --kubelet-insecure-tls

addons:
  cert-manager:
    enabled: true
